### ISSUE TITLE
Machines not displayed

### ISSUE THREAD

**Issue by heuristicus** [pschillinger/rqt_launchtree#2]
The following shows the turtlesim node, but not the machine. setting `default=true` on the machine populates the `machine` field in node properties, but still does not display the machine in the tree.

```
<launch>
  <machine name="turtlesim_machine" address="testaddr"/>
  <node pkg="turtlesim" type="turtlesim_node" name="turtle"/>
</launch>
```

The `setHidden()` function on the `QTreeWidgetItem`  is never called with `True` for machines in [`filter_launch_entry`](https://github.com/pschillinger/rqt_launchtree/blob/b78e84476cc889486532601f0853803e360639c7/src/rqt_launchtree/launchtree_widget.py#L296), which is why they are hidden.

**Comment by pschillinger** [comment]
Apparently forgot about those as there is no separate "machine" checkbox (and I don't think it makes sense to have one).
